[tool.black]
target-version = ['py37']

[tool.mypy]
python_version = "3.7"
no_implicit_optional = true
strict_equality = true
check_untyped_defs = true
warn_unreachable = true
disallow_any_unimported = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
warn_incomplete_stub = true
show_error_codes = true

[[tool.mypy.overrides]]
module = ["pytest.*"]
ignore_missing_imports = true
