name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install packages
      run: |
        python -m pip install --upgrade pip
        pip install black mypy pytest
    - name: Format with black
      run: |
        python -m black --check .
    - name: Test with pytest
      run: |
        python -m pytest -vv tests/
    - name: Check with mypy
      run: |
        mypy tests/
